// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_NPqQE2E_uQ9vlSWlSTvfI5rwgbBLD-I',
    appId: '1:90202137155:web:f14b037eca854ebb686af6',
    messagingSenderId: '90202137155',
    projectId: 'flutter-messenger-cloning',
    authDomain: 'flutter-messenger-cloning.firebaseapp.com',
    databaseURL: 'https://flutter-messenger-cloning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-messenger-cloning.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUb_UsqOHitP2eP0XgSwrhphdMK3vWr2E',
    appId: '1:90202137155:android:22e1f69ab119ce2b686af6',
    messagingSenderId: '90202137155',
    projectId: 'flutter-messenger-cloning',
    databaseURL: 'https://flutter-messenger-cloning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-messenger-cloning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_BYcVwg_s1IdTo3s6vuPxqMA8mZRPtaI',
    appId: '1:90202137155:ios:d91f9ec0aa5995e6686af6',
    messagingSenderId: '90202137155',
    projectId: 'flutter-messenger-cloning',
    databaseURL: 'https://flutter-messenger-cloning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-messenger-cloning.appspot.com',
    iosClientId: '90202137155-3viuimcd0qoa37uj53ejgrjn6r82d8mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_BYcVwg_s1IdTo3s6vuPxqMA8mZRPtaI',
    appId: '1:90202137155:ios:d91f9ec0aa5995e6686af6',
    messagingSenderId: '90202137155',
    projectId: 'flutter-messenger-cloning',
    databaseURL: 'https://flutter-messenger-cloning-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-messenger-cloning.appspot.com',
    iosClientId: '90202137155-3viuimcd0qoa37uj53ejgrjn6r82d8mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );
}
